[package]
name = "ventus-example-function"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde.workspace = true
tokio = { version = "1" }
reqwest = { version = "0.12.3" }

ventus-proto = { path = "../ventus-proto" }
